//Save
var _saveData = array_create(0);

//Varibles
var _save = 
{
	_screenShake : global.screenShakePercent,
	_masterPercent : global.masterPercent,
	_musicPercent : global.musicPercent,
	_blood : global.blood,
	_vibrationPercent : global.vibrationPercent,
	_controllerLayout : global.controllerLayout,
	_weatherSettings : global.weatherSettings,
	_bloom : global.bloom,
	_pb : global.pb,
}
array_push(_saveData, _save);

//turn this into a json n shit
var _string = json_stringify(_saveData);
var _buffer = buffer_create(string_byte_length(_string) +1, buffer_fixed, 1);
buffer_write( _buffer, buffer_string, _string);
buffer_save( _buffer, "save.txt");
buffer_delete( _buffer);


//Add Do not edit file thing
var file;
file = file_text_open_append(working_directory + "save.txt");
file_text_write_string(file, "\n\nDo not edit this file!!!");
file_text_close(file);