weaponCurrent = 0;
disable = false;

ammoMax = [1, 235, 45, 40, 15, 100];
ammoAdd = [0, 70, 10, 25, 6, 40];

shootButton = false;

canshoot = false;
cooldown = 0;
burst = 0;
meleeAngle = -25;
finalMeleeAngle = 0;

backMax = 0;

//Animation
back = 0;
guiY = 0;
muzzleTime = 0;
muzzleIndex = 0;

//Varibles
name = "";
name2 = "";
weaponType = [0];
auto = 0;
burstMax = 0;
burstRate = 0;
damage = 0;
fireDamage = 0;
cooldownMax = 0;
spd = 0;
randomSpd = 0;
pushback = 0;
enemyKnockback = 0;
pattern = 0;
recoil = 0;
screen_shake = 0;
sound = snGunSound;
pickupSound = snChangeWeapon;
sprite = sGun1;
bulletSprite = sBullet1;
bulletType = 0;
bulletTypeSettings = [];
bulletPos = [0, 0];
particleType = 0;
bulletDustType = 0;
amount = 1;
ammoType = [0, 0];
muzzle = 0;
shell = [0, 0, 0];
lazer = 0;
homing = [0];
frict = 0;
bounce = false;
backMax = 0;
zoom = 16;

xypos = [0, 0];
homing_xypos = [0, 0];
handSprite = sGun1Hand;
handColor = oPlayer.player[$ global.currentPlayer][$ "hands"];

weaponChangeCooldown = 0;
wId = 0;

//Nothing
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 0);
ds_map_add(weapon[wId], "BurstRate", 0);
ds_map_add(weapon[wId], "Damage", 3);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 5);
ds_map_add(weapon[wId], "Speed", 10);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 2);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 3);
ds_map_add(weapon[wId], "ScreenShake", 2);
ds_map_add(weapon[wId], "Sound", snGunSound);
ds_map_add(weapon[wId], "Pickup Sound", snChangeWeapon);
ds_map_add(weapon[wId], "Sprite", sPixel);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [0, 0]);
ds_map_add(weapon[wId], "Particle Type", [0, 0, 0]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [0, 0]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 0);
ds_map_add(weapon[wId], "Zoom", 16);

//Pistol
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Pistol");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 3);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 5);
ds_map_add(weapon[wId], "Speed", 10);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 2);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 3);
ds_map_add(weapon[wId], "ScreenShake", 2);
ds_map_add(weapon[wId], "Sound", snGunSound);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunSix);
ds_map_add(weapon[wId], "Sprite", sGun1);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [3, 90]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.4]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [1, 1]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [sShell, 1, 1]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 4);
ds_map_add(weapon[wId], "Zoom", 16);

//Fire Shotgun
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Fire Shotgun");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 0.25);
ds_map_add(weapon[wId], "Fire Damage", 1);
ds_map_add(weapon[wId], "Cooldown", 30);
ds_map_add(weapon[wId], "Speed", 4);
ds_map_add(weapon[wId], "Random Speed", 3);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 18);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundFifteen);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunNine);
ds_map_add(weapon[wId], "Sprite", sGun10);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [1]);
ds_map_add(weapon[wId], "BulletPos", [2, 0]);
ds_map_add(weapon[wId], "Particle Type", [sBulletParticle3, 0, 0.1]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 5);
ds_map_add(weapon[wId], "Ammo", [3, 1]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [sShell2, 1, 30]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0.015);
ds_map_add(weapon[wId], "Bounce", snBulletHit4);
ds_map_add(weapon[wId], "Back", 7);
ds_map_add(weapon[wId], "Zoom", 16);

//Burst M16
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Burst Rifle");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 3);
ds_map_add(weapon[wId], "BurstRate", 5);
ds_map_add(weapon[wId], "Damage", 3);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 16);
ds_map_add(weapon[wId], "Speed", 10);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 2);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0.4);
ds_map_add(weapon[wId], "ScreenShake", 2);
ds_map_add(weapon[wId], "Sound", snGunSoundFour);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunFive);
ds_map_add(weapon[wId], "Sprite", sGun3);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [4, 0]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.4]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [1, 1]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [sShell, 1, 1]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 4);
ds_map_add(weapon[wId], "Zoom", 16);

//Hunting Rifle
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Hunting Rifle");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 9);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 60);
ds_map_add(weapon[wId], "Speed", 12);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundFive);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunTwo);
ds_map_add(weapon[wId], "Sprite", sGun4);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [1]);
ds_map_add(weapon[wId], "BulletPos", [2, 90]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.025]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [2, 1]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [sShell, 1, 30]);
ds_map_add(weapon[wId], "Lazer", 2);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 7);
ds_map_add(weapon[wId], "Zoom", 25);

//Shovel
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Shovel");
ds_map_add(weapon[wId], "Weapon Type", [1, snMelee]); //Woosh Sound on melee
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1); 
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 6);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 30);
ds_map_add(weapon[wId], "Speed", 1);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 3.5);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundSix);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunSeven);
ds_map_add(weapon[wId], "Sprite", sGun5);
ds_map_add(weapon[wId], "BulletSprite", sBullet3);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [0, 0]);
ds_map_add(weapon[wId], "Particle Type", [0, 0, 0]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [0, 0]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", snBulletHit4);
ds_map_add(weapon[wId], "Back", 0);
ds_map_add(weapon[wId], "Zoom", 25);

//Rpg
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "RPG");
ds_map_add(weapon[wId], "Weapon Type", [5]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 4);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 100);
ds_map_add(weapon[wId], "Speed", 0.1);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundSeven);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunThree);
ds_map_add(weapon[wId], "Sprite", sGun16);
ds_map_add(weapon[wId], "BulletSprite", sBullet13);
ds_map_add(weapon[wId], "BulletType", [2]);
ds_map_add(weapon[wId], "BulletPos", [2, 45]);
ds_map_add(weapon[wId], "Particle Type", [sDust, 0, 0.06]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [4, 1]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", -0.025);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 7);
ds_map_add(weapon[wId], "Zoom", 20);

//Homing Rpg
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "HOMING RPG");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 4);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 120);
ds_map_add(weapon[wId], "Speed", 0.1);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundSeven);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunThree);
ds_map_add(weapon[wId], "Sprite", sGun6);
ds_map_add(weapon[wId], "BulletSprite", sBullet4);
ds_map_add(weapon[wId], "BulletType", [2]);
ds_map_add(weapon[wId], "BulletPos", [2, 45]);
ds_map_add(weapon[wId], "Particle Type", [sDust, 0, 0.06]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [4, 1]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [1, 0.05]);
ds_map_add(weapon[wId], "Friction", -0.025);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 7);
ds_map_add(weapon[wId], "Zoom", 20);

//Smg
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "SMG");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", true);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 3);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 4);
ds_map_add(weapon[wId], "Speed", 10);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 1);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 3);
ds_map_add(weapon[wId], "ScreenShake", 2);
ds_map_add(weapon[wId], "Sound", snGunSoundEight);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunFive);
ds_map_add(weapon[wId], "Sprite", sGun7);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [0, 0]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.4]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [1, 1]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [sShell, 1, 1]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 4);
ds_map_add(weapon[wId], "Zoom", 16);

//Chainsaw
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Chainsaw");
ds_map_add(weapon[wId], "Weapon Type", [2, snGunSoundThree]); //Woosh Sound on melee
ds_map_add(weapon[wId], "Automatic", true);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 2);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 5);
ds_map_add(weapon[wId], "Speed", 1);
ds_map_add(weapon[wId], "Random Speed", 3);
ds_map_add(weapon[wId], "Pushback", 0.5);
ds_map_add(weapon[wId], "Enemy Knockback", 0.6);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 1);
ds_map_add(weapon[wId], "Sound", snMeleeTwo);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunFour);
ds_map_add(weapon[wId], "Sprite", sGun8);
ds_map_add(weapon[wId], "BulletSprite", sBullet5);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [0, 0]);
ds_map_add(weapon[wId], "Particle Type", [0, 0, 0]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [0, 0]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 2);
ds_map_add(weapon[wId], "Zoom", 16);

//Grenade Launcher
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Grenade launcher");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 0.5);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 100);
ds_map_add(weapon[wId], "Speed", 3);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundEleven);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunThree);
ds_map_add(weapon[wId], "Sprite", sGun9);
ds_map_add(weapon[wId], "BulletSprite", sBullet6);
ds_map_add(weapon[wId], "BulletType", [2]);
ds_map_add(weapon[wId], "BulletPos", [0, 0]);
ds_map_add(weapon[wId], "Particle Type", [sBulletParticle2, 0, 0.05]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [4, 1]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0.0025);
ds_map_add(weapon[wId], "Bounce", snBulletHit2);
ds_map_add(weapon[wId], "Back", 7);
ds_map_add(weapon[wId], "Zoom", 16);

//Golden Gun
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Golden Gun");
ds_map_add(weapon[wId], "Weapon Type", [4, snMinigunCharge, snMinigunChargeDown]); //Charge up and Charge down
ds_map_add(weapon[wId], "Automatic", true);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 3);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 2);
ds_map_add(weapon[wId], "Speed", 10);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 1.5);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 8);
ds_map_add(weapon[wId], "ScreenShake", 2.5);
ds_map_add(weapon[wId], "Sound", snGunSoundTen);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunEight);
ds_map_add(weapon[wId], "Sprite", sGun11);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [6, 0]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.4]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [1, 1]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [sShell, 1, 1]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 2);
ds_map_add(weapon[wId], "Zoom", 16);

//Lax Blaster
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Lax Blaster");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", true);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 3);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 5);
ds_map_add(weapon[wId], "Speed", 10);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 1.5);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 20);
ds_map_add(weapon[wId], "Recoil", 2);
ds_map_add(weapon[wId], "ScreenShake", 2.5);
ds_map_add(weapon[wId], "Sound", snGunSoundTwelve);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunTen);
ds_map_add(weapon[wId], "Sprite", sGun12);
ds_map_add(weapon[wId], "BulletSprite", sBullet8);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [8, 0]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.4]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 3);
ds_map_add(weapon[wId], "Ammo", [5, 1]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [sShell3, 3, 1]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 4);
ds_map_add(weapon[wId], "Zoom", 16);

//Bow
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Bow");
ds_map_add(weapon[wId], "Weapon Type", [3, snBowStretch]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 5);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 0);
ds_map_add(weapon[wId], "Speed", 12);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 2);
ds_map_add(weapon[wId], "Enemy Knockback", 2.6);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 1);
ds_map_add(weapon[wId], "ScreenShake", 2);
ds_map_add(weapon[wId], "Sound", snGunSoundThirteen);
ds_map_add(weapon[wId], "Pickup Sound", snChangeWeapon);
ds_map_add(weapon[wId], "Sprite", sGun13);
ds_map_add(weapon[wId], "BulletSprite", sBullet9);
ds_map_add(weapon[wId], "BulletType", [1]);
ds_map_add(weapon[wId], "BulletPos", [0, 0]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.1]);
ds_map_add(weapon[wId], "Bullet Dust Type", 1);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [2, 1]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 0);
ds_map_add(weapon[wId], "Zoom", 18);

//Laser Pistol
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Laser Pistol");
ds_map_add(weapon[wId], "Weapon Type", [0]);
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 4);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 14);
ds_map_add(weapon[wId], "Speed", 0);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 2);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 3);
ds_map_add(weapon[wId], "ScreenShake", 2);
ds_map_add(weapon[wId], "Sound", snGunSoundFourteen);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunTen);
ds_map_add(weapon[wId], "Sprite", sGun14);
ds_map_add(weapon[wId], "BulletSprite", sBullet10);
ds_map_add(weapon[wId], "BulletType", [3]);
ds_map_add(weapon[wId], "BulletPos", [7, 14]);
ds_map_add(weapon[wId], "Particle Type", [0, 0, 0]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [5, 1]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 4);
ds_map_add(weapon[wId], "Zoom", 18);

//Solar Cannon
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Solar Cannon");
ds_map_add(weapon[wId], "Weapon Type", [4, snLaserCharge]); //Charge up and Charge down
ds_map_add(weapon[wId], "Automatic", false);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 8);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 55);
ds_map_add(weapon[wId], "Speed", 0);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 4);
ds_map_add(weapon[wId], "Enemy Knockback", 5);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 0);
ds_map_add(weapon[wId], "ScreenShake", 5);
ds_map_add(weapon[wId], "Sound", snGunSoundSixteen);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunTen);
ds_map_add(weapon[wId], "Sprite", sGun15);
ds_map_add(weapon[wId], "BulletSprite", sBullet12);
ds_map_add(weapon[wId], "BulletType", [3]);
ds_map_add(weapon[wId], "BulletPos", [4, 45]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.4]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [5, 2]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 8);
ds_map_add(weapon[wId], "Zoom", 16);

//Revolver
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Revolver");
ds_map_add(weapon[wId], "Weapon Type", [3, snRevolver]);
ds_map_add(weapon[wId], "Automatic", true);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 8);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 35);
ds_map_add(weapon[wId], "Speed", 12);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 2);
ds_map_add(weapon[wId], "Enemy Knockback", 4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 3);
ds_map_add(weapon[wId], "ScreenShake", 4);
ds_map_add(weapon[wId], "Sound", snGunSoundSeventeen);
ds_map_add(weapon[wId], "Pickup Sound", snPickupGunEleven);
ds_map_add(weapon[wId], "Sprite", sGun17);
ds_map_add(weapon[wId], "BulletSprite", sBullet1);
ds_map_add(weapon[wId], "BulletType", [0]);
ds_map_add(weapon[wId], "BulletPos", [3, 90]);
ds_map_add(weapon[wId], "Particle Type", [sLightning, true, 0.2]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [2, 2]);
ds_map_add(weapon[wId], "Muzzle", sMuzzle);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", false);
ds_map_add(weapon[wId], "Back", 10);
ds_map_add(weapon[wId], "Zoom", 16);

//Boomerang
wId += 1;
weapon[wId] = ds_map_create();

ds_map_add(weapon[wId], "Name", "Boomerang");
ds_map_add(weapon[wId], "Weapon Type", [5]);
ds_map_add(weapon[wId], "Automatic", true);
ds_map_add(weapon[wId], "BurstMax", 1);
ds_map_add(weapon[wId], "BurstRate", 1);
ds_map_add(weapon[wId], "Damage", 2);
ds_map_add(weapon[wId], "Fire Damage", 0);
ds_map_add(weapon[wId], "Cooldown", 15);
ds_map_add(weapon[wId], "Speed", 11);
ds_map_add(weapon[wId], "Random Speed", 0);
ds_map_add(weapon[wId], "Pushback", 0);
ds_map_add(weapon[wId], "Enemy Knockback", 2.4);
ds_map_add(weapon[wId], "Pattern", 0);
ds_map_add(weapon[wId], "Recoil", 5);
ds_map_add(weapon[wId], "ScreenShake", 0);
ds_map_add(weapon[wId], "Sound", snMeleeThree);
ds_map_add(weapon[wId], "Pickup Sound", snChangeWeapon);
ds_map_add(weapon[wId], "Sprite", sGun18);
ds_map_add(weapon[wId], "BulletSprite", sGun18Center);
ds_map_add(weapon[wId], "BulletType", [4, -12, 0.02]);
ds_map_add(weapon[wId], "BulletPos", [-1, 0]);
ds_map_add(weapon[wId], "Particle Type", [sBulletParticle4, false, 0.1]);
ds_map_add(weapon[wId], "Bullet Dust Type", 0);
ds_map_add(weapon[wId], "Amount", 1);
ds_map_add(weapon[wId], "Ammo", [0, 0]);
ds_map_add(weapon[wId], "Muzzle", 0);
ds_map_add(weapon[wId], "Shell", [0, 0, 0]);
ds_map_add(weapon[wId], "Lazer", 0);
ds_map_add(weapon[wId], "Homing", [0]);
ds_map_add(weapon[wId], "Friction", 0);
ds_map_add(weapon[wId], "Bounce", -1);
ds_map_add(weapon[wId], "Back", 4);
ds_map_add(weapon[wId], "Zoom", 16);


//Update info
changeWeapon();

//Add Starter ammo
if(global._stage == 0) global.ammo[ammoType[0]] += ammoAdd[ammoType[0]];
clampAmmo();